/*
ITULO: PRIMER PROGRAMA CON COMENTARIOS.
AUTOR: ALFREDO TITO BENAVIDES.
DESCRIPCION:PRIMER PROGRAMA PARA ANALIZAR SU ESTRUCTURA.
FECHA:10/01/24
*/
#include <iostream>//SE TRAE LA LIBRERIA PARA ENTRADA Y SALIDA DE DATOS.

using namespace std;//EL USO DEL ESPACIO DE NOMBRE PARA STD DE LA I/O 

int main()//FUNCION PRINCIPAL MAIN PARA RETORNAR UN ENTERO.
{
	int numero;//DECLARACION DE LA VARIABLE NUMERO COMO ENTERO.
	
	numero = 5 + 5;//ASIGNACION DE LA SUMA 5+5 A LA VARIABLE NUMERO ENTERO.
	/*
	IMPRESION DEL RESULTADO DE LA VARIABLE NUMERO 
	Y ADICION AL FIANL DEL SALTO DE LINES.
	*/ 
	cout << "El valor de numero es: " << numero << endl; 
	return 0;//RETORNO DE 0 PARA FINALIZAR EL PROGRAMA.
}

