/*
TITULO:DEFINIR UNA CONSTANTE LLAMADA PI
AUTOR:ALFREDO TITO BENAVIDES
DESCRIPCION:MOSTRAR EL VALOR DE PI
FECHA:12/01/2024
*/
#include <iostream>
using namespace std;
#define PI 3.1416; //DEFINIMOS UNA CONSTANTE LLAMADA PI

int main(int argc, char *argv[]) {
	//CONTS FLOAT PI = 3.1416; //DEFINIMOS UNA CONSTANTE LLAMADA PI
	cout << "MOSTRANDO EL VALOR DE PI:"<< PI 
	//PI=0;
	return 0;
}

